short_name = "OIP"
name = "Open Industry Project"
major = 4
minor = 5
patch = 0
status = "dev"
module_config = ""
year = 2025
website = "https://github.com/Automation-Standard/Open-Industry-Project"
docs = "latest"
